---

- name: Upgrade Packages
  hosts: servers
  vars:
  gather_facts: True
  become: True
  tasks:

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

